### ISSUE TITLE
How to wrap a struct instantiated in C?

### ISSUE THREAD

**Issue by dagostinelli** [siffiejoe/lua-moon#2]
I have a struct that I have instantiated in C.  I would like to instantiate this from C, push it into Lua such that I can call moon_checkobject() and return it from the stack again, as well as call the instance methods that I've attached using `moon_defobject()`.

I was unable to do this using the stock lua-moon functions.  Here is a bit of code showing the gist.

```
struct MyObject
{
    int x;
    int y;
};

int luaopen_MyObject(lua_State* L)
{
    luaL_Reg const _instance_methods[] = {
        { "__index", __index },
        { "__newindex", __newindex },
        { "SomeMethod", someMethod},
        { NULL, NULL }
    };
    luaL_Reg const _static_methods[] = {
        { "new", __new },
        { NULL, NULL }
    };
    moon_defobject(L, "MyObject", sizeof(struct MyObject), _instance_methods, 0);
    lua_newtable(L);
    luaL_setfuncs(L, _static_methods, 0);
    return 1;
}
```

Later on, to "check" it from the Lua stack, I use `moon_checkobject`.  This works

`moon_checkobject(L, 1, "MyObject");`

I also found `moon_testobject(L, 1, "MyObject")`

My problem comes when I attempt to do this:

```
struct MyObject *instance;
instance = calloc(1, sizeof(struct MyObject));
/* what do I call now to get it on to the stack and 
   properly associated with the object I defined with moon_defobject()?  
   moon_newobject() is not right*/
```

I know that I can push this object on to the stack as userdata.  But that is going around lua-moon.  It isn't getting me what I want (an object that I can add stuff to the metatable -- and it won't call the instance methods that way either)  

I was able to get closer using my own "wrapper".  But I'm not able to extend my objects from lua yet.  The metatable was not accessible through my wrapper.  I could amend the wrapper, but I was wondering instead if I have just misunderstood the lua-moon api. Maybe there's an existing way to do this.  Underneath, it looks like lua-moon is doing a wrapper thing already. (`moon_object_header`).

What is the proper way to do this with lua-moon?  Must I strictly instantiate my class using moon_newobject()?  I'm hoping that isn't the case (since the wrapper I made already almost does everything)

I didn't see anything like a `moon_wrapobject` or `moon_castobject` or something convenient.  Maybe there's an idiomatic way to do this that I'm missing?

Any advice?

**Comment by siffiejoe** [comment]
There's a different function for that: `moon_newpointer()`:

``` C
struct MyObject *instance;
instance = calloc(1, sizeof(struct MyObject));
*moon_newpointer(L, "MyObject", free) = instance;
```

After this the userdata behaves exactly like the ones created via `moon_newobject()`. The example above calls `free()` during the `__gc` metamethod for this userdata. Whether or not that works for you depends on what you are planning to do with the allocated instance outside of Lua.

**Comment by dagostinelli** [comment]
That did it.  Thank you.

One extremely small suggestion to help others find this more easily might be a helper function called `moon_pushobject(L, "MyObject", free, instance);` I think it was the need to dereference that pointer that caused me to skip over this API call.  

Many thanks for the library!

**Comment by siffiejoe** [comment]
There is a reason why the `moon_newpointer()` function is written this way (and the example I've given above is actually bad style -- I just wanted to be as close to your original code as possible). `moon_newpointer()` allocates a new userdata which can cause a memory allocation error and subsequently a Lua error. If you write your code like this

``` C
struct MyObject *instance = calloc(1, sizeof(struct MyObject));
*moon_newpointer(L, "MyObject", free) = instance;
/* ... or ... */
struct MyObject *instance = calloc(1, sizeof(struct MyObject));
moon_pushobject(L, "MyObject", free, instance);
```

you may leak your `MyObject` memory if `lua_newuserdata()` raises. On the other hand, in code like the following

``` C
void** ptr = moon_newpointer(L, "MyObject", free);
struct Myobject* instance = calloc(1, sizeof(struct MyObject));
*ptr = instance;
```

the memory allocation Lua error can only happen _before_ you allocate your own unmanaged memory ...

**Comment by dagostinelli** [comment]
Gotcha.  Thanks.
