### ISSUE TITLE
cast between incompatible function types from ‘moon_object_cast’

### ISSUE THREAD

**Issue by dagostinelli** [siffiejoe/lua-moon#6]
I've come across an issue while compiling. I have been looking at this project in some time (just came back to it).  I wanted to document this issue.  I've upgraded moon and lua to latest versions. 

```
In file included from /home/user/project1/contrib/lua-moon/moon.h:19,
                 from /home/user/project1/contrib/lua-moon/moon.c:14:
/home/user/project1/contrib/lua-moon/moon.c: In function ‘moon_defcast’:
/home/user/project1/contrib/lua-moon/moon.c:528:25: error: cast between incompatible function types from ‘moon_object_cast’ {aka ‘void * (*)(void *)’} to ‘int (*)(lua_State *)’ {aka ‘int (*)(struct lua_State *)’} [-Werror=cast-function-type]
   lua_pushcfunction( L, (lua_CFunction)cast );
                         ^
/home/user/project1/build/packages/lua/src/lua-5.3.5/src/lua.h:350:53: note: in definition of macro ‘lua_pushcfunction’
 #define lua_pushcfunction(L,f) lua_pushcclosure(L, (f), 0)
```

**Comment by dagostinelli** [comment]
lua: 5.3.5

**Comment by dagostinelli** [comment]
Maybe `moon_object_cast` should be typed as:

`typedef int (*moon_object_cast)( lua_State* );`

?

**Comment by dagostinelli** [comment]
On second look, that's probably not right.  I think the root cause is a change in gcc.  It's referenced here:
https://github.com/SELinuxProject/setools/issues/2

Compiling with ` -Wno-cast-function-type` removed the issue.  

I'll leave this issue open here in case you'd like to work on this.

**Comment by siffiejoe** [comment]
I've added extra casts to `void(*)(void)` which hopefully will silence this warning.

**Comment by dagostinelli** [comment]
I think it's fixed.  Thanks!
